# substitutions:
# https://esphome.io/guides/configuration-types.html#substitutions
#   devicename: tmrhrhesp00$deviceNumber
#   deviceIP: 192.168.86.20$deviceNumber

network:
    enable_ipv6: true


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
     static_ip: $deviceIP
     gateway: 192.168.86.1
     subnet: 255.255.255.0
     dns1: 192.168.86.46


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename Fallback Hotspot"
    password: "Vbi8ALgE2P0l"

captive_portal:

web_server:
  port: 80
  include_internal: True

text_sensor:
  - platform: wifi_info
    ip_address:
      name: $devicename IP Address
    # ssid:
    #   name: $devicename Connected SSID
   # bssid:
   #   name: $devicename Connected BSSID
    mac_address:
      name: $devicename Mac Wifi Address
   # scan_results:
    #  name: $devicename Latest Scan Results

button:
  - platform: restart
    name: "$devicename Restart"
  - platform: shutdown
    name: $devicename Shutdown