esphome:
  name: test001
  friendly_name: test001

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "A0fPWLZc3CnxidY82ItRn72y24zkxYg1SOz0L9MDdCc="

ota:
  password: "18698d5640d82f06122c14a669376726"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test001 Fallback Hotspot"
    password: "nJUCEjT3XgV0"

captive_portal:

# Configuration for Ai-Thinker Camera
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  # Image settings
  name: TMRHRHESP004 Camera
  resolution: 640X480
    