esphome:
  name: tmrhrhesp004
  comment: Front Door

  #   - https://github.com/esphome/esphome.git#2022.11.5

external_components:
  - source:
      type: local
      path: my_components
    components: [ esp32_camera ]

esp32:
  board: esp32cam
  framework:
    type: arduino

# Enable logging
# logger:
#   level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "Cp2uuQuMI5OwQz9f3lCVCVlcSxRs2xVFEQ8eco+fr2g="

ota:
  password: "dd5fd5476b463df710388c16d7a3d155"

network:
    enable_ipv6: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip: 
    static_ip: 192.168.86.204
    gateway: 192.168.86.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#   ap:
#     ssid: "Tmrhrhesp004 Fallback Hotspot"
#     password: "zFeraqdzbjjF"

# captive_portal:
    
# web_server:
#   port: 80
#   include_internal: True

# button:
#   - platform: restart
#     name: "tmrhrhesp004 Restart"
#   - platform: shutdown
#     name: "tmrhrhesp004 Shutdown"

# text_sensor:
#   - platform: version
#     name: "tmrhrhesp004 Version"
#   - platform: wifi_info
#     ip_address: 
#       name: TMRHRHESP004 IP

# esp32_camera_web_server:
#   - port: 8080
#     mode: stream
#   - port: 8081
#     mode: snapshot

# Configuration for Ai-Thinker Camera
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  # Image settings
  name: TMRHRHESP004 Camera
  resolution: 160x120

# sensor:
#    - platform: uptime
#      name: TMRHRHESP004 Uptime
#   - platform: wifi_signal
#     name: "TMRHRHESP004 WiFi Signal Sensor"

light:
  - platform: status_led
    name: "TMRHRHESP004 Status LED"
    pin: 4

#esp32_ble_tracker: