substitutions:
  deviceNumber: "3"
  devicename: tmrhrhesp00$deviceNumber
  deviceIP: 192.168.86.20$deviceNumber

esphome:
  name: "$devicename"
  comment: Cat Room

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "BydI86Q1ycxrnfaaezI1Pg6hJZu7JUl+jWeiBi9grRM="

ota:
  - platform: esphome
    password: "79634c3c333563218cc758110472dc82"

<<: !include .common.yaml

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

esp32_camera:
  external_clock:
    pin: GPIO21
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO4, GPIO5, GPIO18, GPIO19, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22

  # Image settings
  name: $devicename Camera
  #resolution: 1024x768

sensor:
  - <<: !include .commonSensor.yaml
  - platform: dht
    model: DHT22
    pin: 32
    temperature:
      name: "$devicename Temperature"
    humidity:
      name: "$devicename Humidity"
    update_interval: 15s