substitutions:
  deviceNumber: "08"
  devicename: tmrhrhesp0$deviceNumber
  deviceIP: 192.168.86.2$deviceNumber

esphome:
  name: $devicename
  comment: Bedroom

# external_components:
#   source: github://pr#5449
#   refresh: 0d
#   components: [network, wifi]

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "m9vGPXDYrizWz7Ci4jFJzwaxzAAJ29VMOTZZWa5CnpM="

ota:
  password: "59287d54ef9d3246645016acd81e4783"

<<: !include .common.yaml

# light:
#   - platform: status_led
#     name: "TMRHRHESP008 Status LED"
#     pin:
#       number: 2
#       inverted: True
# Config Pin	Board Pin	
# 0	          D3	
# 1	          TX	
# 2	          D4	Built-In LED (Inverse)
# 3	          RX	
# 4	          D2	
# 5	          D1	

sensor:
  - <<: !include .commonSensor.yaml

  - platform: homeassistant
    name: "Glucose"
    entity_id: sensor.dexcom_thomas_m_robert_gmail_com_glucose_value
    id: "tmrglucose"

  - platform: dht
    model: DHT22
    pin: 1 #TX
    temperature:
      name: "$devicename Temperature"
      id: "temp"
    humidity:
      name: "$devicename Humidity"
      id: "humid"
    update_interval: 15s

i2c:

# display:
#   - platform: lcd_pcf8574
#     address: 0x27
#     dimensions: 16x2
#     id: lcd
#     lambda: |-
#       it.printf("%.1f%cF %.0f mg/dL%.1f%%", (id(temp).state)*9.0/5.0+32.0, 0xDF, id(tmrglucose).state, id(humid).state);

# switch:
#   - platform: template
#     name: "$devicename Backlight"
#     id: backlight_switch
#     assumed_state: True
#     turn_on_action:
#       - lambda: "id(lcd).backlight(); id(backlight_switch).publish_state(true);"
#     turn_off_action:
#       - lambda: "id(lcd).no_backlight(); id(backlight_switch).publish_state(false);"
