esphome:
  name: tmrhrhesp008-8

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "m9vGPXDYrizWz7Ci4jFJzwaxzAAJ29VMOTZZWa5CnpM="

ota:
  password: "59287d54ef9d3246645016acd81e4783"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tmrhrhesp008-8 Fallback Hotspot"
    password: "4yU5rwcQrCNY"

captive_portal:
    
web_server:
  port: 80
  include_internal: True

button:
  - platform: restart
    name: "TMRHRHESP008 Restart"
  - platform: shutdown
    name: "TMRHRHESP008 Shutdown"

light:
  - platform: status_led
    name: "TMRHRHESP008 Status LED"
    pin: GPIO2

sensor:
  - platform: uptime
    name: TMRHRHESP008 Uptime
  - platform: wifi_signal
    name: "TMRHRHESP008 WiFi Signal Sensor"

  # Config Pin	Board Pin	
  # 0	          D3	
  # 1	          TX	
  # 2	          D4	Built-In LED (Inverse)
  # 3	          RX	
  # 4	          D2	
  # 5	          D1	

  - platform: dht
    model: DHT22
    pin: 1 #TX
    temperature:
      name: "TMRHRHESP008 Temperature"
      id: "TMRHRHESP008_temp"
    humidity:
      name: "TMRHRHESP008 Humidity"
    update_interval: 15s