esphome:
  name: tmrhrhesp008-8
  comment: Bedroom

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "m9vGPXDYrizWz7Ci4jFJzwaxzAAJ29VMOTZZWa5CnpM="

ota:
  password: "59287d54ef9d3246645016acd81e4783"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tmrhrhesp008-8 Fallback Hotspot"
    password: "4yU5rwcQrCNY"

captive_portal:
    
web_server:
  port: 80
  include_internal: True

button:
  - platform: restart
    name: "TMRHRHESP008 Restart"
  - platform: shutdown
    name: "TMRHRHESP008 Shutdown"

light:
  - platform: status_led
    name: "TMRHRHESP008 Status LED"
    pin:
      number: 2
      inverted: True

sensor:
  - platform: uptime
    name: TMRHRHESP008 Uptime
  - platform: wifi_signal
    name: "TMRHRHESP008 WiFi Signal Sensor"

  - platform: homeassistant
    name: "Glucose"
    entity_id: sensor.dexcom_thomas_m_robert_gmail_com_glucose_value
    id: "tmrglucose"

  # Config Pin	Board Pin	
  # 0	          D3	
  # 1	          TX	
  # 2	          D4	Built-In LED (Inverse)
  # 3	          RX	
  # 4	          D2	
  # 5	          D1	

  - platform: dht
    model: DHT22
    pin: 1 #TX
    temperature:
      name: "TMRHRHESP008 Temperature"
      id: "temp"
    humidity:
      name: "TMRHRHESP008 Humidity"
      id: "humid"
    update_interval: 15s

i2c:

display:
  - platform: lcd_pcf8574
    address: 0x27
    dimensions: 16x2
    id: lcd
    lambda: |-
      it.printf("%.1f%cF %.0f mg/dL%.1f%%", (id(temp).state)*9.0/5.0+32.0, 0xDF, id(tmrglucose).state, id(humid).state);

switch:
  - platform: template
    name: "TMRHRHESP008 Backlight"
    id: backlight_switch
    assumed_state: True
    turn_on_action:
      - lambda: "id(lcd).backlight(); id(backlight_switch).publish_state(true);"
    turn_off_action:
      - lambda: "id(lcd).no_backlight(); id(backlight_switch).publish_state(false);"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: TMRHRHESP001 IP Address
    ssid:
      name: TMRHRHESP001 Connected SSID
    # bssid:
    #   name: TMRHRHESP001 Connected BSSID
    mac_address:
      name: TMRHRHESP001 Mac Wifi Address
    # scan_results:
    #  name: TMRHRHESP001 Latest Scan Results