esphome:
  name: tmrhrhesp008-8

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "B6MUAxJoOzpDEgrWxDWv4Hb5c2jsZHwdku4GhmHK0ws="

ota:
  password: "9f34199d45ab751935fd07ecdbc0dad1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tmrhrhesp008-8 Fallback Hotspot"
    password: "HEMWnoUpiEDW"

captive_portal:
    