substitutions:
  deviceNumber: "10"
  devicename: tmrhrhesp0$deviceNumber
  deviceIP: 192.168.86.2$deviceNumber

esphome:
  name: $devicename
  comment: Medicine
  includes:
    - ADXL345.h
  libraries:
    - "Wire"
    - "SPI"
    - "Adafruit BusIO"
    - "Adafruit Unified Sensor"
    - "Adafruit ADXL345"

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "m9vGPXDYrizWz7Ci4jFJzwaxzAAJ29VMOTZZWa5CnpM="

ota:
  password: "59287d54ef9d3246645016acd81e4783"

<<: !include .common.yaml

# light:
#   - platform: status_led
#     name: "TMRHRHESP008 Status LED"
#     pin:
#       number: 2
#       inverted: True
# Config Pin	Board Pin	
# 0	          D3	
# 1	          TX	
# 2	          D4	Built-In LED (Inverse)
# 3	          RX	
# 4	          D2	
# 5	          D1	

sensor:
 # - <<: !include .commonSensor8266.yaml


i2c:
  sda: GPIO14
  scl: GPIO12

custom_component:
  - lambda: |-
      auto adxl345 = new ADXL345Sensor();
      return {adxl345};      
    components:
      - id: adxl345

binary_sensor:
  platform: custom
  lambda: |-
    return {static_cast<ADXL345Sensor *>(id(adxl345))->activity};    
  binary_sensors:
    - name: "Activity"
      id: adxl_activity
      device_class: moving