esphome:
  name: tmrhrhesp006
  comment: Basement

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "BDSik0DyLvQybAI2U7VvWl/yPH9sNQJX6RKsRdoPvrc="

ota:
  password: "637ad8549bf28a8cec2d6af580ef7164"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tmrhrhesp006 Fallback Hotspot"
    password: "ZplrNTuk57x9"

captive_portal:
    
web_server:
  port: 80
  include_internal: True

button:
  - platform: restart
    name: "TMRHRHESP006 Restart"
  - platform: shutdown
    name: "TMRHRHESP006 Shutdown"

sensor:
  - platform: uptime
    name: TMRHRHESP006 Uptime
  - platform: wifi_signal
    name: "TMRHRHESP006 WiFi Signal Sensor"

  - platform: dht
    model: DHT22
    pin: 18
    temperature:
      name: "TMRHRHESP006 Temperature"
      id: "tmrhrhesp006_temp"
    humidity:
      name: "TMRHRHESP006 Humidity"
    update_interval: 15s

binary_sensor:
  - platform: gpio
    pin: 34
    name: "TMRHRHESP006 Blue Push Button"
  - platform: gpio
    pin: 35
    name: "TMRHRHESP006 Red Push Button"

light:
  - platform: binary
    name: "TMRHRHESP006 RED LED"
    output: light_output
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Slow Pulse"
          update_interval: 2s

output:
  - id: light_output
    platform: gpio
    pin: 32