substitutions:
  deviceNumber: "06"
  devicename: tmrhrhesp0$deviceNumber
  deviceIP: 192.168.86.2$deviceNumber

esphome:
  name: $devicename
  comment: Basement

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "BDSik0DyLvQybAI2U7VvWl/yPH9sNQJX6RKsRdoPvrc="

ota:
  password: "637ad8549bf28a8cec2d6af580ef7164"

<<: !include .common.yaml

sensor:
  - <<: !include .commonSensor.yaml

  - platform: dht
    model: DHT22
    pin: 18
    temperature:
      name: "$devicename Temperature"
    humidity:
      name: "$devicename Humidity"
    update_interval: 15s

binary_sensor:
  - platform: gpio
    pin: 34
    name: "$devicename Blue Push Button"
  - platform: gpio
    pin: 35
    name: "$devicename Red Push Button"

light:
  - platform: binary
    name: "$devicename RED LED"
    output: light_output

output:
  - id: light_output
    platform: gpio
    pin: 32