esphome:
  name: tmrhrhesp012
  friendly_name: tmrhrhesp012

esp32:
  board: esp32cam
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "pMWe4NqBKZ4F2PGCvF1/LlgDSEAVE0az37b0ZR3c0LA="

ota:
  - platform: esphome
    password: "804c6867374e8fad47adde1dc52a3a01"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: 192.168.86.212
    gateway: 192.168.86.1
    subnet: 255.255.0.0
    dns1: 192.168.86.45

captive_portal:
    
esp32_ble_tracker:

ble_client:
  - mac_address: 5C:D6:1F:EC:1D:C6
    id: scale

sensor:
  - platform: ble_client
    type: characteristic
    ble_client_id: scale
    name: "Weight"
    service_uuid: '181D'
    characteristic_uuid: '00002A9C-0000-1000-8000-00805F9B34FB'
    update_interval: 1s
    #icon: 'mdi:battery'
    #unit_of_measurement: '%'
  - platform: ble_client
    type: characteristic
    ble_client_id: scale
    name: "Composition"
    service_uuid: '181B'
    characteristic_uuid: '00002A9C-0000-1000-8000-00805F9B34FB'
    update_interval: 1s

