esphome:
  name: tmrhrhesp001
  comment: "Living Room"

  #fixes mirror image problem
#external_components:
#  - source: github://esphome/esphome@dev
#    components: [ max7219digit ]

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  
  encryption:
    key: "uJ2NpNEjoeyd97hM1ueo3B8zm6k5g39pGxGqkSmtLIM="

ota:
  password: "22ce48a66a5653f5aa4d63e4ea5d6558"

network:
    enable_ipv6: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
     static_ip: 192.168.86.201
     gateway: 192.168.86.1
     subnet: 255.255.255.0
     dns1: 192.168.86.46


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "TMRHRHESP001 Fallback Hotspot"
    password: "Vbi8ALgE2P0l"

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: TMRHRHESP001 IP Address
    ssid:
      name: TMRHRHESP001 Connected SSID
   # bssid:
   #   name: TMRHRHESP001 Connected BSSID
    mac_address:
      name: TMRHRHESP001 Mac Wifi Address
   # scan_results:
    #  name: TMRHRHESP001 Latest Scan Results

sensor:
  - platform: dht
    model: DHT22
    pin: 25
    temperature:
      name: "tmrhrhesp001 Temperature"
      id: "lrtemp"
    humidity:
      name: "tmrhrhesp001 Humidity"
      filters:
#       - offset: -20.0
    update_interval: 15s

  - platform: internal_temperature
    name: "tmrhrhesp001 Internal Temperature"

  - platform: homeassistant
    name: "Glucose"
    entity_id: sensor.dexcom_thomas_m_robert_gmail_com_glucose_value
    id: "tmrglucose"
    
# Example configuration entry
web_server:
  port: 80
  include_internal: True

button:
  - platform: restart
    name: "tmrhrhesp001 Restart"
  - platform: shutdown
    name: tmrhrhesp001 Shutdown

font:
  - file: "fonts/pixelmix.ttf"
    id: digit_font
    size: 8
    glyphs: '0123456789na'
  - file: "fonts/pixelmix.ttf"
    id: digit_fontt
    size: 5
    glyphs: 'mg/dl'

graph:
# Show bare-minimum auto-ranged graph
- id: single_temperature_graph
  sensor: tmrglucose
  line_thickness: 1
  duration: 40min
  width: 8
  height: 8
  border: false

# Example configuration entry
spi:
  clk_pin: 27
  mosi_pin: 32
  
display:
  - platform: max7219digit
    cs_pin: 14
    num_chips: 4
    intensity: 1
    scroll_enable: false
    rotate_chip: 0
    update_interval: 1s
    lambda: |-

      it.printf(0, 0, id(digit_font), "%.0f", id(tmrglucose).state);
      it.print(it.get_width(), 0, id(digit_fontt), TextAlign::TOP_RIGHT, "mg/dl");

  - platform: max7219digit
    cs_pin: 33
    num_chips: 1
    intensity: 1
    scroll_mode: CONTINUOUS
    rotate_chip: 90
    update_interval: 1min
    lambda: |-
      it.graph(0, 0, id(single_temperature_graph));

#      it.printf(0, 0, id(digit_font), "%.1f°F", id(lrtemp).state*9.0/5.0+32.0);


